services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/opt/homebrew/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s # 20초 동안 헬스 체크 진행
      retries: 10 # 헬스 체크 진행 시간
  backend:
    env_file:
      - .env
    image: openjdk:21
    ports:
      - '8080:8080'
    volumes:
      - ./application.yml:/app/application.yml
      - ./E-Commerce-0.0.1-SNAPSHOT.jar:/app/E-Commerce-0.0.1-SNAPSHOT.jar
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "/app/E-Commerce-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://highv.cpcuesoama6y.us-east-1.rds.amazonaws.com:3306/highv

      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qwer1234
      SPRING_REDIS_HOST: redis
      AUTH_ISSUER: highv.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - backend
    image: nginx
  mysql:
    image: mysql:latest
    ports:
      - '23306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q!w@e#r$1234
      MYSQL_DATABASE: highv
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
